# Generated by Django 2.2.5 on 2020-03-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_auto_20200304_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTYBNK', 'Nifty Bank'), ('NFTY', 'Nifty')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SS', 'SIDEWAYS_SELL'), ('SELL', 'SELL'), ('SB', 'SIDEWAYS_BUY'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
    ]
