# Generated by Django 2.2.5 on 2020-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_auto_20200304_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sortedstockdashboardreport',
            name='stoploss_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortedstockdashboardreport',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SB', 'SIDEWAYS_BUY'), ('BUY', 'BUY'), ('SS', 'SIDEWAYS_SELL'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
    ]
