# Generated by Django 2.2.5 on 2020-03-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0006_auto_20200327_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_analysis.OrderBook'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('RE', 'Rejected'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SS', 'SIDEWAYS_SELL'), ('SB', 'SIDEWAYS_BUY'), ('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
    ]
