# Generated by Django 2.2.5 on 2020-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0009_auto_20200401_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M5', '5 Minute'), ('M60', '60 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Rejected'), ('OP', 'Open'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SB', 'SIDEWAYS_BUY'), ('SS', 'SIDEWAYS_SELL'), ('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
    ]
