# Generated by Django 2.2.5 on 2020-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0010_auto_20200401_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='exit_price',
            new_name='stoploss',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M10', '10 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('RE', 'Rejected'), ('OP', 'Open'), ('CA', 'Cancelled')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SS', 'SIDEWAYS_SELL'), ('BUY', 'BUY'), ('SELL', 'SELL'), ('SB', 'SIDEWAYS_BUY')], default='BUY', max_length=20),
        ),
    ]
