# Generated by Django 2.2.5 on 2020-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0013_auto_20200402_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['entry_time']},
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('RE', 'Rejected'), ('OP', 'Open'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='', max_length=10),
        ),
    ]
