# Generated by Django 2.2.5 on 2020-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0014_auto_20200408_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='entry_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='pl',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='stoploss',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='target_price',
        ),
        migrations.AddField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('EX', 'Exit'), ('ET', 'Entry')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stoploss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SS', 'SIDEWAYS_SELL'), ('BUY', 'BUY'), ('SB', 'SIDEWAYS_BUY'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
    ]
