# Generated by Django 2.2.5 on 2020-04-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0015_auto_20200410_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
