# Generated by Django 2.2.5 on 2020-04-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0016_auto_20200417_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M5', '5 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('RE', 'Rejected'), ('OP', 'Open'), ('CA', 'Cancelled')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('SS', 'SIDEWAYS_SELL'), ('SB', 'SIDEWAYS_BUY'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
    ]
