# Generated by Django 2.2.5 on 2020-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0018_auto_20200425_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategytimestamp',
            old_name='diff',
            new_name='entry_price',
        ),
    ]
