# Generated by Django 2.2.5 on 2020-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0019_auto_20200426_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('PR', 'PRIMARY'), ('SC', 'SECONDARY')], default='SC', max_length=10),
        ),
    ]
