# Generated by Django 2.2.5 on 2020-06-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0023_auto_20200525_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='strategy',
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('ET', 'Entry'), ('EX', 'Exit')], default='ET', max_length=20),
        ),
        migrations.AddField(
            model_name='symbol',
            name='entry_strategy',
            field=models.ManyToManyField(blank=True, related_name='entry_strategy_symbols', to='market_analysis.Strategy'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='exit_strategy',
            field=models.ManyToManyField(blank=True, related_name='exit_strategy_symbols', to='market_analysis.Strategy'),
        ),
    ]
