# Generated by Django 2.2.5 on 2020-06-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0024_auto_20200606_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategytimestamp',
            name='indicator',
        ),
        migrations.AddField(
            model_name='strategytimestamp',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_analysis.Strategy'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('PR', 'PRIMARY'), ('SP', 'SUPPORTING'), ('SC', 'SECONDARY')], default='SC', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('ET', 'Entry'), ('EX', 'Exit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('CO', 'Completed'), ('RE', 'Rejected'), ('OP', 'Open')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('SS', 'SIDEWAYS_SELL'), ('SB', 'SIDEWAYS_BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('SP', 'Support'), ('PR', 'Primary'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='entry_strategy',
            field=models.ManyToManyField(blank=True, limit_choices_to={'strategy_type': 'ET'}, related_name='entry_strategy_symbols', to='market_analysis.Strategy'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exit_strategy',
            field=models.ManyToManyField(blank=True, limit_choices_to={'strategy_type': 'EX'}, related_name='exit_strategy_symbols', to='market_analysis.Strategy'),
        ),
    ]
