# Generated by Django 2.2.5 on 2020-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0025_auto_20200610_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.AddField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SC', 'Secondary'), ('SP', 'Support'), ('PR', 'Primary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('RE', 'Rejected'), ('CO', 'Completed'), ('OP', 'Open')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('ET', 'Entry'), ('EX', 'Exit')], default='ET', max_length=20),
        ),
    ]
