# Generated by Django 2.2.5 on 2020-07-08 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0028_auto_20200618_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortedstockslist',
            name='added',
            field=models.CharField(choices=[('ML', 'Manually'), ('AT', 'Automatically')], default='AT', max_length=10),
        ),
        migrations.CreateModel(
            name='DeployedStrategies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(choices=[('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M10', '10 Minute'), ('M30', '30 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour')], default='M5', max_length=50)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_analysis.Strategy')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_strategies', to='market_analysis.Symbol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
