# Generated by Django 2.2.5 on 2020-07-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0029_auto_20200708_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployedstrategies',
            options={'verbose_name_plural': 'DeployedStrategies'},
        ),
        migrations.AddField(
            model_name='deployedstrategies',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='deployedstrategies',
            unique_together={('symbol', 'strategy', 'timeframe')},
        ),
    ]
