# Generated by Django 2.2.5 on 2020-07-10 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0030_auto_20200709_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M30', '30 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='strategy',
            field=models.ForeignKey(limit_choices_to={'strategy_type': 'ET'}, on_delete=django.db.models.deletion.CASCADE, to='market_analysis.Strategy'),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M30', '30 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour'), ('1D', '1 Day')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CA', 'Cancelled'), ('CO', 'Completed'), ('RE', 'Rejected')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SP', 'Support'), ('PR', 'Primary'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='deployedstrategies',
            unique_together={('symbol', 'strategy', 'timeframe', 'entry_type')},
        ),
    ]
