# Generated by Django 2.2.5 on 2020-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0031_auto_20200710_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='trade_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M30', '30 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M30', '30 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('1D', '1 Day')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('CA', 'Cancelled'), ('RE', 'Rejected'), ('OP', 'Open')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTYBNK', 'Nifty Bank'), ('NFTY', 'Nifty')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='added',
            field=models.CharField(choices=[('AT', 'Automatically'), ('ML', 'Manually')], default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
    ]
