# Generated by Django 2.2.5 on 2020-07-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0032_auto_20200710_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployedstrategies',
            options={'verbose_name_plural': 'Deployed Strategies'},
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M30', '30 Minute'), ('1H', '1 Hour'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M60', '60 Minute'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M30', '30 Minute'), ('1H', '1 Hour'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M60', '60 Minute'), ('M5', '5 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('CO', 'Completed'), ('RE', 'Rejected'), ('OP', 'Open')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='exit_strategy',
            field=models.ForeignKey(blank=True, limit_choices_to={'strategy_type': 'EX'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='market_analysis.Strategy'),
        ),
        migrations.AlterField(
            model_name='strategytimestamp',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_analysis.DeployedStrategies'),
        ),
    ]
