# Generated by Django 2.2.5 on 2020-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0033_auto_20200711_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EI', 'EquityIntraday'), ('EF', 'EquityFutures')], default='EI', max_length=10),
        ),
    ]
