# Generated by Django 2.2.5 on 2020-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0034_auto_20200712_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('symbol_name', models.CharField(max_length=100)),
                ('strategy_name', models.CharField(max_length=100)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry_time', models.DateTimeField()),
                ('stoploss', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('strategy_status', models.CharField(max_length=50)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exit_time', models.DateTimeField()),
                ('entry_type', models.CharField(max_length=10)),
                ('candle_type', models.CharField(max_length=20)),
                ('pl', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='strategy',
            name='backtesting_ready',
            field=models.BooleanField(default=False, help_text='Check if you think that strategy is ready for backtesting'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1H', '1 Hour'), ('1D', '1 Day'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('1H', '1 Hour'), ('1D', '1 Day'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('OP', 'Open'), ('RE', 'Rejected'), ('CO', 'Completed')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='added',
            field=models.CharField(choices=[('ML', 'Manually'), ('AT', 'Automatically')], default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SP', 'Support'), ('PR', 'Primary'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
    ]
