# Generated by Django 2.2.5 on 2020-07-20 23:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0036_auto_20200720_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M30', '30 Minute'), ('1H', '1 Hour'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M30', '30 Minute'), ('1H', '1 Hour'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M30', '30 Minute'), ('1H', '1 Hour'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CA', 'Cancelled'), ('RE', 'Rejected'), ('CO', 'Completed')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTYBNK', 'Nifty Bank'), ('NFTY', 'Nifty')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SP', 'Support'), ('SC', 'Secondary'), ('PR', 'Primary')], default='SU', max_length=20),
        ),
    ]
