# Generated by Django 2.2.5 on 2020-07-20 23:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0037_auto_20200720_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour'), ('1D', '1 Day')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('EX', 'Exit'), ('ET', 'Entry')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cancelled'), ('OP', 'Open'), ('CO', 'Completed'), ('RE', 'Rejected')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SC', 'Secondary'), ('SP', 'Support')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('EX', 'Exit'), ('ET', 'Entry')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M10', '10 Minute'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour'), ('1D', '1 Day')], max_length=24, null=True),
        ),
    ]
