# Generated by Django 2.2.5 on 2020-07-25 12:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0039_auto_20200724_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('1H', '1 Hour'), ('M60', '60 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('1D', '1 Day'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('1H', '1 Hour'), ('M60', '60 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('ET', 'Entry'), ('EX', 'Exit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Rejected'), ('CA', 'Cancelled'), ('OP', 'Open'), ('CO', 'Completed')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='added',
            field=models.CharField(choices=[('ML', 'Manually'), ('AT', 'Automatically')], default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EI', 'EquityIntraday'), ('EF', 'EquityFutures')], default='EI', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('ET', 'Entry'), ('EX', 'Exit')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1D', '1 Day'), ('M30', '30 Minute'), ('M15', '15 Minute'), ('1H', '1 Hour'), ('M60', '60 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute')], max_length=24, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('symbol', 'exchange')},
        ),
        migrations.AddConstraint(
            model_name='sortedstockslist',
            constraint=models.UniqueConstraint(fields=('symbol', 'entry_type', 'created_at'), name='unique_stock_by_entrytype_date'),
        ),
    ]
