# Generated by Django 2.2.5 on 2020-07-25 13:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0040_auto_20200725_1207'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sortedstockslist',
            name='unique_stock_by_entrytype_date',
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M15', '15 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M15', '15 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('RE', 'Rejected'), ('CA', 'Cancelled'), ('OP', 'Open')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTYBNK', 'Nifty Bank'), ('NFTY', 'Nifty')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SP', 'Support'), ('PR', 'Primary'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EF', 'EquityFutures'), ('EI', 'EquityIntraday')], default='EI', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M15', '15 Minute')], max_length=24, null=True),
        ),
    ]
