# Generated by Django 2.2.5 on 2020-07-26 17:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0041_auto_20200725_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_backtested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1H', '1 Hour'), ('M60', '60 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('1H', '1 Hour'), ('M60', '60 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M10', '10 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('EX', 'Exit'), ('ET', 'Entry')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Rejected'), ('OP', 'Open'), ('CA', 'Cancelled'), ('CO', 'Completed')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EI', 'EquityIntraday'), ('EF', 'EquityFutures')], default='EI', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('EX', 'Exit'), ('ET', 'Entry')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1H', '1 Hour'), ('M60', '60 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M10', '10 Minute')], max_length=24, null=True),
        ),
    ]
