# Generated by Django 2.2.5 on 2020-07-26 19:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0042_auto_20200726_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('candle_type', models.CharField(max_length=20)),
                ('strategy_name', models.CharField(max_length=100)),
                ('symbol_name', models.CharField(max_length=100)),
                ('entry_type', models.CharField(max_length=10)),
                ('backtest_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='last_backtested',
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M5', '5 Minute')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('ET', 'Entry'), ('EX', 'Exit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CO', 'Completed'), ('CA', 'Cancelled'), ('OP', 'Open'), ('RE', 'Rejected')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('BUY', 'BUY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('SC', 'Secondary'), ('PR', 'Primary'), ('SP', 'Support')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('ET', 'Entry'), ('EX', 'Exit')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M15', '15 Minute'), ('M60', '60 Minute'), ('1H', '1 Hour'), ('M30', '30 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M5', '5 Minute')], max_length=24, null=True),
        ),
    ]
