# Generated by Django 2.2.5 on 2020-08-08 16:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0044_auto_20200808_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stratrgy',
            new_name='strategy',
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('EX', 'Exit'), ('ET', 'Entry')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Rejected'), ('CA', 'Cancelled'), ('OP', 'Open'), ('CO', 'Completed')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='added',
            field=models.CharField(choices=[('AT', 'Automatically'), ('ML', 'Manually')], default='AT', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EF', 'EquityFutures'), ('EI', 'EquityIntraday')], default='EI', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('EX', 'Exit'), ('ET', 'Entry')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M60', '60 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M30', '30 Minute'), ('M5', '5 Minute'), ('1H', '1 Hour')], max_length=24, null=True),
        ),
    ]
