# Generated by Django 2.2.5 on 2020-08-16 21:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0046_auto_20200808_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M30', '30 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('1H', '1 Hour')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='deployedstrategies',
            name='timeframe',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M30', '30 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('1H', '1 Hour')], default='M5', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('ET', 'Entry'), ('EX', 'Exit')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RE', 'Rejected'), ('CO', 'Completed'), ('OP', 'Open'), ('CA', 'Cancelled')], default='OP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='priority_type',
            field=models.CharField(choices=[('PR', 'Primary'), ('SP', 'Support'), ('SC', 'Secondary')], default='SU', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_for',
            field=models.CharField(choices=[('EI', 'EquityIntraday'), ('EF', 'EquityFutures')], default='EI', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('ET', 'Entry'), ('EX', 'Exit')], default='ET', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='timeframe',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M5', '5 Minute'), ('M30', '30 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('1H', '1 Hour')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='trade_manually',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=8, null=True),
        ),
    ]
