# Generated by Django 2.2.5 on 2020-08-22 13:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0047_auto_20200816_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='trade_realtime',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL')], help_text='Enabling this will call realtime strategies for trading', max_length=8, null=True),
        ),
    ]
