# Generated by Django 2.2.5 on 2020-08-22 19:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0048_auto_20200822_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_realtime',
            field=models.BooleanField(default=False, help_text='Enabling this will consider strategy as realtime strategy where strategy will call on ticker data not on candle data'),
        ),
    ]
