# Generated by Django 2.2.5 on 2020-09-16 23:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0050_auto_20200830_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortedstockdashboardreport',
            name='current_price',
        ),
        migrations.AddField(
            model_name='sortedstockdashboardreport',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
