# Generated by Django 2.2.5 on 2019-09-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_type', models.CharField(choices=[('5 Minute', 'minute_5')], default=None, max_length=50, null=True)),
                ('open_price', models.IntegerField(blank=True, null=True, verbose_name='Candle Open Price')),
                ('high_price', models.IntegerField(blank=True, null=True, verbose_name='Candle High Price')),
                ('low_price', models.IntegerField(blank=True, null=True, verbose_name='Candle Low Price')),
                ('close_price', models.IntegerField(blank=True, null=True, verbose_name='Candle Close Price')),
                ('ltt', models.IntegerField(blank=True, null=True, verbose_name='Candle Last Traded Time')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
