# Generated by Django 2.2.5 on 2019-09-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=100, null=True)),
                ('response_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
    ]
