# Generated by Django 2.2.5 on 2019-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0002_auto_20190920_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Candle Close Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Candle High Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Candle Low Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Candle Open Price'),
        ),
    ]
