# Generated by Django 2.2.5 on 2019-09-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_auto_20190921_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='candle',
            name='ltt',
        ),
        migrations.AddField(
            model_name='candle',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('1D', '1 Day'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('closing_price', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=20, null=True)),
                ('isin', models.CharField(max_length=50)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='symbols', to='market_analysis.MasterContract')),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market_analysis.Symbol'),
        ),
    ]
