# Generated by Django 2.2.5 on 2019-09-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_auto_20190922_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Recently Updated'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('1D', '1 Day'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
    ]
