# Generated by Django 2.2.5 on 2019-10-10 22:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0005_auto_20190926_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='asks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='atp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='candle',
            name='bids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='candle',
            name='lower_circuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='candle',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='candle',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='candle',
            name='upper_circuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='candle',
            name='vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
    ]
