# Generated by Django 2.2.5 on 2019-10-11 16:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0006_auto_20191010_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='closing_price',
            new_name='last_day_closing_price',
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_day_opening_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_day_vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='asks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='candle',
            name='bids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1D', '1 Day'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute')], default=None, max_length=50, null=True),
        ),
    ]
