# Generated by Django 2.2.5 on 2019-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0007_auto_20191011_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
    ]
