# Generated by Django 2.2.5 on 2019-10-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0008_auto_20191018_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Recently Updated'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M5', '5 Minute'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='last_day_vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Day Traded Volume'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Buy Quantity'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Sell Quantity'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Traded Volume'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
