# Generated by Django 2.2.5 on 2019-10-25 09:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market_analysis', '0008_auto_20191024_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
        migrations.AddField(
            model_name='candle',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 25, 9, 17, 39, 623957)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastercontract',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mastercontract',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 25, 9, 17, 55, 143096)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 25, 9, 18, 12, 852696)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 25, 9, 18, 23, 338587)),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='user',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M5', '5 Minute'), ('1D', '1 Day'), ('M10', '10 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
    ]
