# Generated by Django 2.2.5 on 2019-10-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0009_auto_20191025_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('initial_balance', models.DecimalField(decimal_places=2, help_text='Initial balance at the starting of month', max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market_analysis.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=150, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('1D', '1 Day'), ('M5', '5 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Profit & Loss')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='market_analysis.BankDetail')),
            ],
        ),
    ]
