# Generated by Django 2.2.5 on 2019-10-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0012_auto_20191030_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M10', '10 Minute'), ('M60', '60 Minute'), ('M15', '15 Minute'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StrategyTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_analysis.Indicator')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_analysis.SortedStocksList')),
            ],
        ),
    ]
