# Generated by Django 2.2.5 on 2019-10-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0009_auto_20191023_0943'),
        ('market_analysis', '0013_auto_20191030_2130'),
    ]

    operations = [
    ]
