# Generated by Django 2.2.5 on 2019-10-31 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0014_merge_20191030_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name_plural': 'Credentials'},
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='updated',
        ),
        migrations.AddField(
            model_name='credentials',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='market_analysis.UserProfile'),
        ),
        migrations.AddField(
            model_name='strategytimestamp',
            name='diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='market_analysis.UserProfile'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('M5', '5 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='last_day_vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
