# Generated by Django 2.2.5 on 2019-11-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0016_auto_20191104_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='for_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
    ]
