# Generated by Django 2.2.5 on 2019-11-07 12:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0017_auto_20191104_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('ltp', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('close', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('open', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('high', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('low', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('vtt', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('atp', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('total_buy_qty', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('total_sell_qty', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('lower_circuit', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('upper_circuit', models.IntegerField(blank=True, null=True, verbose_name='Last Traded Price')),
                ('bids', django.contrib.postgres.fields.jsonb.JSONField()),
                ('asks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ltt', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M10', '10 Minute'), ('M60', '60 Minute'), ('1D', '1 Day'), ('M15', '15 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
