# Generated by Django 2.2.5 on 2019-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0019_auto_20191107_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortedstockslist',
            name='stock_type',
            field=models.CharField(choices=[('S', 'SELL'), ('B', 'BUY')], default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('1D', '1 Day'), ('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute')], default=None, max_length=50, null=True),
        ),
    ]
