# Generated by Django 2.2.5 on 2019-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0020_auto_20191113_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortedstockslist',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M60', '60 Minute'), ('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute')], default=None, max_length=50, null=True),
        ),
    ]
