# Generated by Django 2.2.5 on 2019-12-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0021_auto_20191113_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerData',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='vtt',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bearable_loss',
            field=models.IntegerField(blank=True, default=0, verbose_name='Bearable loss in percent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expected_profit',
            field=models.IntegerField(blank=True, default=0, verbose_name='Expected profit in percent'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_historical_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_live_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candle',
            name='atp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average Traded Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('M60', '60 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candle',
            name='lower_circuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lower Circuit Price'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Buy Quantity'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Sell Quantity'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='upper_circuit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Upper Circuit Price'),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategytimestamp',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='market_analysis.SortedStocksList'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='last_day_vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Day Traded Volume'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_buy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Buy Quantity'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='total_sell_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Sell Quantity'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='vtt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Traded Volume'),
        ),
    ]
