# Generated by Django 2.2.5 on 2019-12-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0022_auto_20191219_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PU', 'Public Holiday')], default='PU', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('1D', '1 Day'), ('M15', '15 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
    ]
