# Generated by Django 2.2.5 on 2020-02-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0023_auto_20191223_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M60', '60 Minute'), ('M10', '10 Minute'), ('M5', '5 Minute'), ('M15', '15 Minute'), ('1D', '1 Day')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('SB', 'SIDEWAYS_BUY'), ('SS', 'SIDEWAYS_SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.CreateModel(
            name='PreMarketOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('NFTY', 'Nifty'), ('NFTYBNK', 'Nifty Bank')], default='NFTYBNK', max_length=20)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_percent', models.FloatField(blank=True, null=True)),
                ('previous_close', models.FloatField(blank=True, null=True)),
                ('buy_qty_ato', models.IntegerField(blank=True, null=True)),
                ('sell_qty_ato', models.IntegerField(blank=True, null=True)),
                ('total_buy_qty', models.IntegerField(blank=True, null=True)),
                ('total_sell_qty', models.IntegerField(blank=True, null=True)),
                ('total_trade_qty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_market', to='market_analysis.Symbol')),
            ],
        ),
    ]
