# Generated by Django 2.2.5 on 2020-02-24 23:02

from django.db import migrations, models

def create_market_indicator(apps, schema_editor):
    indicators = ["MACD", "STOCHASTIC", "PDHL", "OHL", "LONGSHORT"]
    Indicator = apps.get_model("market_analysis", "Indicator")
    counter = 0
    for i in indicators:
        try:
            indi = Indicator.objects.get(name=i)
        except:
            indi = Indicator.objects.create(name=i, value=counter)
        counter += 1



class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0024_auto_20200208_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedStockDashboardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('entry_type', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('pl', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M15', '15 Minute'), ('M60', '60 Minute'), ('M10', '10 Minute'), ('1D', '1 Day'), ('M5', '5 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='premarketorderdata',
            name='sector',
            field=models.CharField(choices=[('NFTYBNK', 'Nifty Bank'), ('NFTY', 'Nifty')], default='NFTYBNK', max_length=20),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SS', 'SIDEWAYS_SELL'), ('SB', 'SIDEWAYS_BUY'), ('SELL', 'SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
        migrations.RunPython(create_market_indicator),
    ]
