# Generated by Django 2.2.5 on 2020-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0025_auto_20200224_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_type',
            field=models.CharField(choices=[('M5', '5 Minute'), ('M10', '10 Minute'), ('M15', '15 Minute'), ('1D', '1 Day'), ('M60', '60 Minute')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockdashboardreport',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockdashboardreport',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortedstockslist',
            name='entry_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('SB', 'SIDEWAYS_BUY'), ('SS', 'SIDEWAYS_SELL'), ('BUY', 'BUY')], default='BUY', max_length=20),
        ),
    ]
